---

- name: Make Sure We Have Some Basics
  package:
    name: "{{ item }}"
    state: "latest"
  with_items: "{{ clwells_packages }}"

- name: Add Group
  group:
    name="{{ clwells_unix_group }}"
    state="present"

- name: Add User
  user:
    name: "{{ clwells_unix_user }}"
    group: "{{ clwells_unix_group }}"
    groups: "wheel"
    home: "{{ clwells_unix_home }}"
    move_home: "yes"
    shell: "{{ clwells_unix_shell }}"
    state: "present"

- name: Let Wheel Be Root
  lineinfile:
    "dest=/etc/sudoers state=present regexp='^%wheel' line='%wheel ALL=(ALL) NOPASSWD: ALL'"

- name: Install .emacs
  get_url:
    url: "https://raw.githubusercontent.com/clwells/bootstrap/master/dot-emacs"
    dest: "{{ clwells_unix_home }}/.emacs"
    owner: "{{ clwells_unix_user }}"
    group: "{{ clwells_unix_group }}"
    mode: 0644
    force: true

- name: Make Sure .emacs.d Exists
  file:
    name: "{{ clwells_unix_home }}/.emacs.d"
    owner: "{{ clwells_unix_user }}"
    group: "{{ clwells_unix_group }}"
    mode: 0711
    state: "directory"

- name: Install PHP mode
  get_url:
    url: "https://raw.githubusercontent.com/clwells/bootstrap/master/php-mode.el"
    dest: "{{ clwells_unix_home }}/.emacs.d/php-mode.el"
    owner: "{{ clwells_unix_user }}"
    group: "{{ clwells_unix_group }}"
    mode: 0644
    force: true

- name: Install .bash_profile
  get_url:
    url: "https://raw.githubusercontent.com/clwells/bootstrap/master/dot-bash_profile"
    dest: "{{ clwells_unix_home }}/.bash_profile"
    owner: "{{ clwells_unix_user }}"
    group: "{{ clwells_unix_group }}"
    mode: 0644

- name: Setup My Key
  authorized_key:
    user: "{{ clwells_unix_user }}"
    key: "https://raw.githubusercontent.com/clwells/key/master/id_rsa.pub"

- name: At Least Make Sure EDITOR=emacs
  lineinfile:
    dest: "{{ clwells_unix_home }}/.bash_profile"
    line: "export EDITOR=emacs"

- name: Kill Emacs Backups as Root
  lineinfile:
    dest: "/root/.emacs"
    line: "(setq make-backup-files nil)"
  ignore_errors: true

- name: Setup GH Commit Name
  shell: git config --global user.name "Chris Wells"
  become: yes
  become_user: "{{ clwells_unix_user }}"

- name: Setup GH Commit Email
  shell: git config --global user.email "chris@nexcess.net"
  become: yes
  become_user: "{{ clwells_unix_user }}"
